config/routes.rb
Rails.application.routes.draw do

  resources :sales

  resources :shops

  resources :users

  get 'main/index' , to: "main#index"
  get 'main/brand' , to: "main#brand"
  get 'main/login' , to: "main#login"
  get 'main/myPage' , to: "main#myPage"
  get 'main/setup' , to: "main#setup"
  get 'main/shop' , to: "main#shop"
  get 'main/sign' , to: "main#sign"

  root to: "main#index"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:title, :content, :shop-id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :tel, :time, :offday, :address, :station, :message)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saleboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/brand.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title Saleboard
          %link{:href => "bootstrap-3.3.2-dist/css/bootstrap.min.css", :rel => "stylesheet"}
            %link{:href => "style.css", :rel => "stylesheet", :type => "text/css"}
              / Bootstrap
              / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
              / WARNING: Respond.js doesn't work if you view the page via file://
              /[if lt IE 9]
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    #wrapper
      .contents
        #header.row
          .col-md-4
            .table
              .table-cell
                .input-group
                  %input.form-control{:placeholder => "キーワードを入力", :type => "text"}
                    %span.input-group-btn
                      %button.btn.btn-default{:type => "button"} 検索
                / /input-group
          .col-md-4.logo
            .table
              %a.table-cell{:href => "index.html"} Saleboard
          .col-md-4.sign
            .table
              %a.table-cell{:href => "sign.html"} 新規登録
        .row.top-header
          .col-md-3.kara
          .col-md-3
            .table
              %a.table-cell.active{:href => "brand.html"} ブランド
          .col-md-3
            .table
              %a.table-cell.active エリア
          .col-md-3.kara
        #main
          .brand
            = image_tag "beams-logo.png"
            .brand.detail
              %h3 happy life solution company BEAMS
              %p
                我々BEAMSはモノを通して文化をつくる”カルチャーショップ”を目指しています。
                %br
                  即ち、モノを手にいれた満足感の先にある、そのモノが生まれた背景や時代性といったことを含む情報を共有することで、物質的満足以上の価値を提供するということです。
          .row.title-header
            .col-md-4
            .col-md-4
              .table
                .table-cell
                  Stores
            .col-md-4
          .row.stores
            %a.col-sm-6.col-md-4{:href => "shop.html"}
              .thumbnail
                .img-back.beams
                  .caption
                    %h4 BEAMS 渋谷
                %span.point-sticky.point-sticky-l SALE
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.hikarie
                  .caption
                    %h4 BEAMS ヒカリエ
                %span.point-sticky.point-sticky-l SALE
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.kitasenju
                  .caption
                    %h4 BEAMS 北千住
          .row.stores
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.marunouchi
                  .caption
                    %h4 BEAMS 丸の内
                %span.point-sticky.point-sticky-l SALE
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.shinjuku
                  .caption
                    %h4 BEAMS 新宿
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.yokohama
                  .caption
                    %h4 BEAMS 横浜
                %span.point-sticky.point-sticky-l SALE
          .row.stores
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.rumine
                  .caption
                    %h4 BEAMS 横浜ルミネ
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.nagoya
                  .caption
                    %h4 BEAMS 名古屋
                %span.point-sticky.point-sticky-l SALE
            %a.col-sm-6.col-md-4
              .thumbnail
                .img-back.osaka
                  .caption
                    %h4 BEAMS 大阪
          %button.btn.btn-default.center-block{:type => "submit"} もっと見る
        #footer
          .row
            .panel-footer Copyright © 2015 Saleboard All Rights Reserved.
    / jQuery (necessary for Bootstrap's JavaScript plugins)
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    / Include all compiled plugins (below), or include individual files as needed
    %script{:src => "js/bootstrap.min.js"}

app/views/main/index.html.haml
/ !!!
/ %html{:lang => "ja"}
/   %head
/     %meta{:charset => "utf-8"}
/       %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
/         %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
/           %title Saleboard
/           %link{:href => "bootstrap-3.3.2-dist/css/bootstrap.min.css", :rel => "stylesheet"}
/             %link{:href => "style.css", :rel => "stylesheet", :type => "text/css"}
/               / Bootstrap
/               / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
/               / WARNING: Respond.js doesn't work if you view the page via file://
/               /[if lt IE 9]
/                 <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
/                 <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
/   %body
#wrapper
  .contents
    #header.row
      .col-md-4
        .table
          .table-cell
            .input-group
              %input.form-control{:placeholder => "キーワードを入力", :type => "text"}
                %span.input-group-btn
                  %button.btn.btn-default{:type => "button"} 検索
            / /input-group
      .col-md-4.logo
        .table
          %a.table-cell{:href => "index.html"} Saleboard
      .col-md-4.sign
        .table
          %a.table-cell{:href => "sign.html"} 新規登録
    .row.top-header
      .col-md-3.kara
      .col-md-3
        .table
          %a.table-cell.active{:href => "brand.html"} ブランド
      .col-md-3
        .table
          %a.table-cell.active エリア
      .col-md-3.kara
    .row
      .top.table
        .text.table-cell.middle.center
          好きなお店のおトクな情報を受け取ろう
    #main
      .row.title-header
        .col-md-4
        .col-md-4
          .table
            .table-cell
              Stores
        .col-md-4
      .row.stores
        %a.col-sm-6.col-md-4{:href => "shop.html"}
          .thumbnail
            .img-back.beams
              .caption
                %h4 BEAMS 渋谷
            %span.point-sticky.point-sticky-l SALE
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.apc
              .caption
                %h4 A.P.C 青山店
            %span.point-sticky.point-sticky-l SALE
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.coach
              .caption
                %h4 COACH 渋谷店
      .row.stores
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.diesel
              .caption
                %h4 DIESEL 明治通り店
            %span.point-sticky.point-sticky-l SALE
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.kastane
              .caption
                %h4 kastane 原宿店
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.nano
              .caption
                %h4 nano・universe 渋谷店
            %span.point-sticky.point-sticky-l SALE
      .row.stores
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.tocca
              .caption
                %h4 TOCCA 青山店
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.topshop
              .caption
                %h4 TOPSHOP 原宿店
            %span.point-sticky.point-sticky-l SALE
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.xgirl
              .caption
                %h4 X-girl 原宿店
      .row.stores
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.adidas
              .caption
                %h4 adidas 新宿店
            %span.point-sticky.point-sticky-l SALE
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.paulsmith
              .caption
                %h4 PaulSmith 明治通り店
        %a.col-sm-6.col-md-4
          .thumbnail
            .img-back.diamant
              .caption
                %h4 RoungeDiamant 新宿店
      %button.btn.btn-default.center-block{:type => "submit"} もっと見る
    #footer
      .row
        .panel-footer Copyright © 2015 Saleboard All Rights Reserved.
/ jQuery (necessary for Bootstrap's JavaScript plugins)
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
/ Include all compiled plugins (below), or include individual files as needed
%script{:src => "js/bootstrap.min.js"}

app/views/main/login.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title Saleboard
          %link{:href => "bootstrap-3.3.2-dist/css/bootstrap.min.css", :rel => "stylesheet"}
            %link{:href => "style.css", :rel => "stylesheet", :type => "text/css"}
              / Bootstrap
              / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
              / WARNING: Respond.js doesn't work if you view the page via file://
              /[if lt IE 9]
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    #wrapper
      .contents
        #header.row
          .col-md-4
            .table
              .table-cell
                .input-group
                  %input.form-control{:placeholder => "キーワードを入力", :type => "text"}
                    %span.input-group-btn
                      %button.btn.btn-default{:type => "button"} 検索
                / /input-group
          .col-md-4.logo
            .table
              %p.table-cell Saleboard
          .col-md-4.sign
            .table
              %a.table-cell{:href => "sign.html"} 新規登録
        .row.top-header
          .col-md-3.kara
          .col-md-3
            .table
              %a.table-cell.active{:href => "brand.html"} ブランド
          .col-md-3
            .table
              %a.table-cell.active エリア
          .col-md-3.kara
        #footer
          .row
            .panel-footer Copyright © 2015 Saleboard All Rights Reserved.
    / jQuery (necessary for Bootstrap's JavaScript plugins)
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    / Include all compiled plugins (below), or include individual files as needed
    %script{:src => "js/bootstrap.min.js"}

app/views/main/myPage.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title Saleboard
          %link{:href => "bootstrap-3.3.2-dist/css/bootstrap.min.css", :rel => "stylesheet"}
            %link{:href => "style.css", :rel => "stylesheet", :type => "text/css"}
              / Bootstrap
              / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
              / WARNING: Respond.js doesn't work if you view the page via file://
              /[if lt IE 9]
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    #wrapper
      .contents
        #header.row
          .col-md-4
            .table
              .table-cell
                .input-group
                  %input.form-control{:placeholder => "キーワードを入力", :type => "text"}
                    %span.input-group-btn
                      %button.btn.btn-default{:type => "button"} 検索
                / /input-group
          .col-md-4.logo
            .table
              %a.table-cell{:href => "index.html"} Saleboard
          .col-md-4.sign
            .table
              .table-cell
                = image_tag "account.png", class: "account"
        .row.top-header
          .col-md-3.kara
          .col-md-3
            .table
              %a.table-cell.active{:href => "brand.html"} ブランド
          .col-md-3
            .table
              %a.table-cell.active エリア
          .col-md-3.kara
        #main
          .row.title-header
            .col-md-4
            .col-md-4
              .table
                .table-cell
                  マイリスト
            .col-md-4
          .row.stores
            .col-sm-6.col-md-4
              %a.thumbnail{:href => "shop.html"}
                .img-back.beams
                  .caption
                    %h4 BEAMS 渋谷
                %span.point-sticky.point-sticky-l SALE
              %a.btn{:href => "#"} 登録解除
            .col-sm-6.col-md-4
              %a.thumbnail
                .img-back.apc
                  .caption
                    %h4 A.P.C 青山店
                %span.point-sticky.point-sticky-l SALE
              %a.btn{:href => "#"} 登録解除
            .col-sm-6.col-md-4
              %a.thumbnail
                .img-back.coach
                  .caption
                    %h4 COACH 渋谷店
              %a.btn{:href => "#"} 登録解除
        #footer
          .row
            .panel-footer Copyright © 2015 Saleboard All Rights Reserved.
    / jQuery (necessary for Bootstrap's JavaScript plugins)
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    / Include all compiled plugins (below), or include individual files as needed
    %script{:src => "js/bootstrap.min.js"}

app/views/main/setup.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title Saleboard
          %link{:href => "bootstrap-3.3.2-dist/css/bootstrap.min.css", :rel => "stylesheet"}
            %link{:href => "style.css", :rel => "stylesheet", :type => "text/css"}
              / Bootstrap
              / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
              / WARNING: Respond.js doesn't work if you view the page via file://
              /[if lt IE 9]
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body
    #wrapper
      .contents
        #header.row
          .col-md-4
            .table
              .table-cell
                .input-group
                  %input.form-control{:placeholder => "キーワードを入力", :type => "text"}
                    %span.input-group-btn
                      %button.btn.btn-default{:type => "button"} 検索
                / /input-group
          .col-md-4.logo
            .table
              %a.table-cell{:href => "index.html"} Saleboard
          .col-md-4.sign
            .table
              .table-cell
                %img.account{:src => "img/account.png"}
        .row.top-header
          .col-md-3.kara
          .col-md-3
            .table
              %a.table-cell.active{:href => "brand.html"} ブランド
          .col-md-3
            .table
              %a.table-cell.active エリア
          .col-md-3.kara
        #main
          .form.block-center
            %form.form-inline
              .form-group
                %h2 設定
                %label.sr-only{:for => "exampleInputEmail3"} name
                %input#exampleInputEmail3.form-control{:placeholder => "YU YOKOI", :type => "email"}
              %br
                .form-group
                  %label.sr-only{:for => "exampleInputPassword3"} E-Mail
                  %input#exampleInputPassword3.form-control{:placeholder => "yu.hanabi18@gmail.com", :type => "password"}
                %br
                  .form-group
                    %label.sr-only{:for => "exampleInputPassword3"} Password
                    %input#exampleInputPassword3.form-control{:placeholder => "パスワード", :type => "password"}
                  %br
                    .form-group
                      %label.sr-only{:for => "exampleInputPassword3"} Password2
                      %input#exampleInputPassword3.form-control{:placeholder => "パスワード再入力", :type => "password"}
                    %br
                      %button.btn.btn-default.new{:type => "submit"} 更新
        #footer
          .row
            .panel-footer Copyright © 2015 Saleboard All Rights Reserved.
    / jQuery (necessary for Bootstrap's JavaScript plugins)
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    / Include all compiled plugins (below), or include individual files as needed
    %script{:src => "js/bootstrap.min.js"}

app/views/sales/_form.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :shop-id
    = f.number_field :shop-id
  .actions
    = f.submit 'Save'

app/views/sales/edit.html.haml
%h1 Editing sale

= render 'form'

= link_to 'Show', @sale
\|
= link_to 'Back', sales_path

app/views/sales/index.html.haml
%h1 Listing sales

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Shop-id
      %th
      %th
      %th

  %tbody
    - @sales.each do |sale|
      %tr
        %td= sale.title
        %td= sale.content
        %td= sale.shop-id
        %td= link_to 'Show', sale
        %td= link_to 'Edit', edit_sale_path(sale)
        %td= link_to 'Destroy', sale, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sale', new_sale_path

app/views/sales/new.html.haml
%h1 New sale

= render 'form'

= link_to 'Back', sales_path

app/views/sales/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @sale.title
%p
  %b Content:
  = @sale.content
%p
  %b Shop-id:
  = @sale.shop-id

= link_to 'Edit', edit_sale_path(@sale)
\|
= link_to 'Back', sales_path

app/views/shops/_form.html.haml
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      %ul
        - @shop.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :tel
    = f.text_field :tel
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :offday
    = f.text_field :offday
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :station
    = f.text_field :station
  .field
    = f.label :message
    = f.text_area :message
  .actions
    = f.submit 'Save'

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
%h1 Listing shops

%table
  %thead
    %tr
      %th Name
      %th Tel
      %th Time
      %th Offday
      %th Address
      %th Station
      %th Message
      %th
      %th
      %th

  %tbody
    - @shops.each do |shop|
      %tr
        %td= shop.name
        %td= shop.tel
        %td= shop.time
        %td= shop.offday
        %td= shop.address
        %td= shop.station
        %td= shop.message
        %td= link_to 'Show', shop
        %td= link_to 'Edit', edit_shop_path(shop)
        %td= link_to 'Destroy', shop, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.haml
%h1 New shop

= render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @shop.name
%p
  %b Tel:
  = @shop.tel
%p
  %b Time:
  = @shop.time
%p
  %b Offday:
  = @shop.offday
%p
  %b Address:
  = @shop.address
%p
  %b Station:
  = @shop.station
%p
  %b Message:
  = @shop.message

= link_to 'Edit', edit_shop_path(@shop)
\|
= link_to 'Back', shops_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit '登録'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path